name: Actions CI

on:
  push:
    branches: [ main ]
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
env:
  VERBOSITY: 'Minimal'
  CONFIGURATION: 'Release'
  DOTNET_NOLOGO: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

jobs: 
  Build:
    name: Build on .NET Core ${{ matrix.dotnet }}    
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: ['8.0.204']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract build and copyright information into variables
      id: info
      run: |
        echo "BUILD=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV
        echo "COPYRIGHT=$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)" >> $GITHUB_ENV
        
    - name: Show build information
      run: |
        echo BUILD=${{ env.BUILD }}
        echo COPYRIGHT=${{ env.COPYRIGHT }}
           
    - name: Show .NET Core information
      run: dotnet --info
            
    - name: Build and pack runtime libraries project
      working-directory: src/  
      run: >- 
        dotnet pack ./TinyOS.Pipelink -p:BuildNumber="${{ env.BUILD }}" -p:Copyright="${{ env.COPYRIGHT }}"
        --version-suffix prebuild.${{ env.BUILD }}
        --verbosity ${{ env.VERBOSITY }}
        --configuration ${{ env.CONFIGURATION }}
        --include-symbols
        --output ./builds/artifacts

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Prebuild.${{ env.BUILD }} Packages
        path: "./src/builds/artifacts/**/*.nupkg"
        if-no-files-found: error
